print ("Hello World!")
print ("Hello Again")
print ("I like typing this.")
print ("This is fun.")
print ('Yay! Printing.')
print ("I'd much rather you 'not'.")
print("adding my line in the pythonsscrip python and unix and git exper")
print ('I "said" do not touch this.')
